*** Variables ***

${BTN_MENU_TRANSFERENCIA}    id=btn-TRANSFERÊNCIA
${INPUT_CONTA}    //input[@type='accountNumber']
${INPUT_DIGITO}    //input[@type='digit']
${INPUT_VALOR}    //input[@type='transferValue']
${INPUT_DESCRICAO}    //input[@type='description']
${BTN_TRANSFERIR}    text=Transferir agora

${MODAL_SUCESSO}    text=Transferencia realizada com sucesso
${BTN_FECHAR_MODAL}    id=btnCloseModal
${BTN_VOLTAR_HOME}    id=btnBack 
